ModelArguments:
  base_model_name: T5 # options are T5, T5-v1, mT5
  t5_model_name: "google-t5/t5-base"
  checkpoint_path: "last_checkpoint"
  feature_dim: 208
  hidden_dim: 768
  
DatasetArguments:
  test_dataset_path: 'SSL.keypoints.test_signers_test_sentences.0.h5'
  test_labels_dataset_path: 'SSL.annotation.test_signers_test_sentences.csv'

EvaluationArguments:
  results_save_path: "results"
  batch_size: 16
